### ISSUE TITLE
Incorrect work with characters

### ISSUE THREAD

**Issue by slaw-ik** [asaf050/js-scanner-detection#1]
Wen you scan a text (not only numbers) it returns blank characters like "Shift" for capital characters.

Listening on keypress instead of keydown fixes the problem

https://github.com/asaf050/js-scanner-detection/blob/fcaab3add6ac9f30330188b5bb550e66408f12ce/src/lib/index.js#L25

**Comment by asaf050** [comment]
Hi @slaw-ik , thank you for your pull request.
Closing due to https://github.com/asaf050/js-scanner-detection/pull/2
