### ISSUE TITLE
TypeError: scannerDetector.stopScanning is not a function

### ISSUE THREAD

**Issue by ivx-mda** [asaf050/js-scanner-detection#5]
Apologies in advance, this is my first reported issue and fully expect I'm doing something wrong. 

The stopScanning method is not a recognized method on the scannerDetector object

I can see the [method in src](https://github.com/asaf050/js-scanner-detection/blob/master/src/lib/index.js), but when I log the scannerDetector object, it does not have the stopScanning method
![image](https://user-images.githubusercontent.com/81973862/116139311-7fd8fa00-a69b-11eb-9543-8ea766ef0e7a.png)

Hopefully this codesandbox is helpful: https://codesandbox.io/s/muddy-shape-ik8jf?file=/src/index.js

I copy/pasted the code from the readme, and added some buttons to start/stop scanning; i caught and logged the error when using the stop scanning method.

**Comment by ivx-mda** [comment]
small update FWIW: 

I simply pasted the code from [index.js in src](https://github.com/asaf050/js-scanner-detection/blob/master/src/lib/index.js) into a file in my project and stopScanning() works just fine in that way. Maybe it's just that the NPM package is out of sync with Github somehow, although they appear to be the same version (1.0.3)

**Comment by asaf050** [comment]
Hi,
I resolved this issue

Thanks
